/* SPDX-License-Identifier: GPL-3.0-only
 * quanta-freeze — QSC -> pure static Faust codegen (spec §7)
 * Copyright (c) 2026 DeMoD LLC.
 *
 * Emits a self-contained .dsp: shared f64 tables as waveform literals,
 * per-voice atom tables + branch-free letrec-style index walkers, seeded
 * LCG residual through an inline TPT SVF bank. Arithmetic order mirrors
 * quanta-render exactly so the null test (§7.4) is meaningful.
 *
 * --verify : emit unity constants instead of UI sliders (golden renders).
 * --k N    : prune atoms with rank >= N before emission (frozen K, §7).
 */
#include "../include/qsc.h"

static void emit_table(FILE *o, const char *name, const double *v, uint32_t n){
    fprintf(o, "%s = waveform{", name);
    for (uint32_t i = 0; i < n; i++)
        fprintf(o, "%s%.17g", i ? "," : "", v[i]);
    fprintf(o, "};\n");
}

int main(int argc, char **argv){
    const char *inpath = NULL, *outpath = "out.dsp", *luapath = NULL;
    uint32_t K = 0xFFFFFFFF; int verify = 0;
    for (int i = 1; i < argc; i++){
        if (!strcmp(argv[i], "-o") && i+1 < argc) outpath = argv[++i];
        else if (!strcmp(argv[i], "--k") && i+1 < argc) K = (uint32_t)strtoul(argv[++i],0,0);
        else if (!strcmp(argv[i], "--lua") && i+1 < argc) luapath = argv[++i];
        else if (!strcmp(argv[i], "--verify")) verify = 1;
        else inpath = argv[i];
    }
    if (!inpath){ fprintf(stderr,"usage: quanta-freeze in.qsc [-o out.dsp] [--k N] [--verify]\n"); return 2; }

    Qsc q;
    if (qsc_read(inpath, &q)){ fprintf(stderr, "freeze: qsc_read failed\n"); return 1; }

    /* K-prune (frozen artifact has no runtime K gate, §7) */
    uint32_t m = 0;
    for (uint32_t i = 0; i < q.h.atom_count; i++)
        if (q.atoms[i].rank < K) q.atoms[m++] = q.atoms[i];
    q.h.atom_count = m;

    /* optional Lua score sidecar for the demod-ui quanta panel (§10) */
    if (luapath){
        FILE *lo = fopen(luapath, "w");
        if (lo){
            fprintf(lo, "-- generated by quanta-freeze v0.1.0 (demod-quanta score sidecar)\n"
                        "return {\n  sr = %u, len = %llu, voices = %u, seed = \"0x%08X\",\n"
                        "  atoms = {\n",
                    q.h.sample_rate, (unsigned long long)q.h.source_len,
                    q.h.voice_count, q.h.noise_seed);
            for (uint32_t i = 0; i < m; i++){
                const QscAtom *a = &q.atoms[i];
                fprintf(lo, "    {r=%u,o=%u,d=%u,f=%.6g,a=%.6g,l=%u},\n",
                        a->rank, a->onset, a->dur, (double)a->freq,
                        (double)a->amp, a->layer);
            }
            fprintf(lo, "  }\n}\n");
            fclose(lo);
            fprintf(stderr, "freeze: score sidecar -> %s\n", luapath);
        }
    }

    int P = q.h.voice_count;
    uint32_t *voff = calloc(P + 1, sizeof(uint32_t));
    for (uint32_t i = 0; i < m; i++) voff[q.atoms[i].voice + 1]++;
    for (int v = 0; v < P; v++) voff[v+1] += voff[v];

    double wtab[QSC_TAB], stab[QSC_TAB];
    qsc_build_tables(wtab, stab);

    FILE *o = fopen(outpath, "w");
    if (!o){ fprintf(stderr, "freeze: cannot open %s\n", outpath); return 1; }

    fprintf(o,
        "// demod-quanta frozen artifact — generated by quanta-freeze v0.1.0\n"
        "// source_len=%llu sr=%u atoms=%u voices=%d seed=0x%08X %s\n"
        "// Deterministic static resynthesis (spec §7). Compile: -double -ftz 2.\n"
        "// SKILL v2: dcblocker on output; saturator/OU-LFO intentionally waived (§7).\n"
        "declare name \"demod-quanta-frozen\";\n"
        "declare license \"Generated output — property of the score owner (spec §13)\";\n"
        "import(\"stdfaust.lib\");\n\n"
        "RATE = %.17g;\nNTAB = %d;\n\n",
        (unsigned long long)q.h.source_len, q.h.sample_rate, m, P,
        q.h.noise_seed, verify ? "[verify]" : "",
        (double)q.h.sample_rate, QSC_TAB);

    /* shared tables — byte-identical to the C reference (parity contract) */
    emit_table(o, "wtab", wtab, QSC_TAB);
    emit_table(o, "stab", stab, QSC_TAB);
    fprintf(o,
        "wt(i) = wtab, int(i) : rdtable;\n"
        "st(i) = stab, int(i) : rdtable;\n"
        "wlin(p) = wt(i0) + fr*(wt(i1) - wt(i0)) with {\n"
        "  pc = max(0.0, p);\n"
        "  i0 = min(int(pc), NTAB-1); i1 = min(i0+1, NTAB-1);\n"
        "  fr = pc - float(i0);\n"
        "};\n"
        "slin(p) = st(a) + fr*(st(b) - st(a)) with {\n"
        "  i0 = int(p); fr = p - float(i0);\n"
        "  a = i0 & (NTAB-1); b = (i0+1) & (NTAB-1);\n"
        "};\n"
        "tim = (+(1) ~ _) - 1;\n\n");

    if (verify)
        fprintf(o, "g0 = 1.0; g1 = 1.0; g2 = 1.0; gm = 1.0;\n\n");
    else
        fprintf(o,
        "g0 = ba.db2linear(hslider(\"h:quanta/[0]tonal [unit:dB]\",0,-60,12,0.1)) : si.smoo;\n"
        "g1 = ba.db2linear(hslider(\"h:quanta/[1]transient [unit:dB]\",0,-60,12,0.1)) : si.smoo;\n"
        "g2 = ba.db2linear(hslider(\"h:quanta/[2]residual [unit:dB]\",0,-60,12,0.1)) : si.smoo;\n"
        "gm = ba.db2linear(hslider(\"h:quanta/[3]master [unit:dB]\",0,-60,12,0.1)) : si.smoo;\n\n");

    /* ---------------- per-voice atom tables + walkers ---------------- */
    for (int v = 0; v < P; v++){
        uint32_t a0 = voff[v], n = voff[v+1] - voff[v];
        double *tb = malloc(sizeof(double) * (n + 1));
        char nm[32];
        for (uint32_t i = 0; i < n; i++) tb[i] = (double)q.atoms[a0+i].onset;
        tb[n] = 1e30;                                   /* sentinel */
        snprintf(nm, 32, "on%d", v);  emit_table(o, nm, tb, n + 1);
        for (uint32_t i = 0; i < n; i++) tb[i] = (double)q.atoms[a0+i].dur;
        snprintf(nm, 32, "du%d", v);  emit_table(o, nm, tb, n);
        for (uint32_t i = 0; i < n; i++) tb[i] = (double)q.atoms[a0+i].freq;
        snprintf(nm, 32, "fq%d", v);  emit_table(o, nm, tb, n);
        for (uint32_t i = 0; i < n; i++) tb[i] = (double)q.atoms[a0+i].amp;
        snprintf(nm, 32, "am%d", v);  emit_table(o, nm, tb, n);
        for (uint32_t i = 0; i < n; i++)
            tb[i] = (double)q.atoms[a0+i].phase * (1.0/(2.0*M_PI));
        snprintf(nm, 32, "ph%d", v);  emit_table(o, nm, tb, n);
        for (uint32_t i = 0; i < n; i++) tb[i] = (double)q.atoms[a0+i].layer;
        snprintf(nm, 32, "ly%d", v);  emit_table(o, nm, tb, n);
        free(tb);

        fprintf(o,
            "voice%d = amv*win*sv*act%s with {\n"
            "  n = %u;\n"
            "  onr(i) = on%d, int(i) : rdtable;\n"
            "  idx = (inc ~ _) with { inc(p) = p + ((p+1 < n) & (tim >= onr(p+1))); };\n"
            "  o = onr(idx);\n"
            "  d = du%d, int(idx) : rdtable;\n"
            "  amv = am%d, int(idx) : rdtable;\n"
            "  fqv = fq%d, int(idx) : rdtable;\n"
            "  phv = ph%d, int(idx) : rdtable;\n"
            "  lyv = ly%d, int(idx) : rdtable;\n"
            "  lg = (lyv < 0.5)*g0 + (lyv > 0.5)*g1;\n"
            "  tl = tim - o;\n"
            "  act = (tl >= 0.0) & (tl < d);\n"
            "  win = wlin(tl / d * float(NTAB));\n"
            "  ph = fqv * tl / RATE + phv;\n"
            "  sv = slin((ph - float(int(ph))) * float(NTAB));\n"
            "};\n\n",
            v, verify ? "" : "*lg", n + 0u, v, v, v, v, v, v);
    }

    /* ---------------- residual: LCG -> inline TPT SVF bank ---------------- */
    fprintf(o,
        "lcgs = (step ~ _) with { step(s) = (s*%d + %d + %d) & %d; };\n"
        "nz = float(lcgs)/1073741824.0 - 1.0;\n"
        "svf(a1,a2,a3) = (rec(a1,a2,a3) ~ (_,_)) : (!,!,_) with {\n"
        "  rec(a1_,a2_,a3_, ic1, ic2, x) = ic1n, ic2n, bp with {\n"
        "    v3 = x - ic2; v1 = a1_*ic1 + a2_*v3; v2 = ic2 + a2_*ic1 + a3_*v3;\n"
        "    bp = 0.25*v1; ic1n = 2.0*v1 - ic1; ic2n = 2.0*v2 - ic2;\n"
        "  };\n"
        "};\n",
        QSC_LCG_A, QSC_LCG_C, (int32_t)q.h.noise_seed, QSC_LCG_M);

    uint32_t FR = q.h.residual_frames;
    fprintf(o, "FR = %u;\nfpos = float(tim)/%.17g;\n"
        "ef0 = min(int(fpos), FR-1);\nef1 = min(ef0+1, FR-1);\n"
        "efr = fpos - float(ef0);\n", FR, (double)q.h.residual_hop);

    double *gt = malloc(sizeof(double) * (FR ? FR : 1));
    for (int b = 0; b < QSC_BANDS; b++){
        char nm[32];
        for (uint32_t f = 0; f < FR; f++)
            gt[f] = qsc_gain_dq(q.res_gains[(size_t)f*QSC_BANDS + b]);
        snprintf(nm, 32, "gt%d", b);
        emit_table(o, nm, gt, FR);
        double fc = qsc_band_fc(b);
        double g  = tan(M_PI * fc / q.h.sample_rate);
        double k  = 1.0 / QSC_BAND_Q;
        double a1 = 1.0/(1.0 + g*(g + k)), a2 = g*a1, a3 = g*a2;
        fprintf(o,
            "env%d = e0 + efr*(e1 - e0) with { e0 = gt%d, int(ef0) : rdtable;"
            " e1 = gt%d, int(ef1) : rdtable; };\n"
            "res%d = (nz : svf(%.17g, %.17g, %.17g)) * env%d;\n",
            b, b, b, b, a1, a2, a3, b);
    }
    free(gt);

    /* ---------------- mix: fixed left-assoc order (§12.4) ---------------- */
    fprintf(o, "\nvsum = ");
    if (P == 0) fprintf(o, "0.0");
    for (int v = 0; v < P; v++) fprintf(o, "%svoice%d", v ? " + " : "", v);
    fprintf(o, ";\nres = ");
    if (FR == 0) fprintf(o, "0.0");
    for (int b = 0; FR && b < QSC_BANDS; b++) fprintf(o, "%sres%d", b ? " + " : "", b);
    fprintf(o, ";\n");
    fprintf(o,
        "dcb = _ <: (_, mem : -) : + ~ *(0.995);\n"
        "process = (vsum + res%s)%s : dcb;\n",
        verify ? "" : "*g2", verify ? "" : " * gm");

    fclose(o);
    fprintf(stderr, "freeze: %u atoms across %d voices -> %s%s\n",
            m, P, outpath, verify ? " [verify mode]" : "");
    qsc_free(&q); free(voff);
    return 0;
}
