/*
 * demod-rt — Deterministic RT Audio Process
 *
 * Copyright (C) 2025–2026 DeMoD LLC
 * SPDX-License-Identifier: GPL-3.0-only
 *
 * This binary is exec'd by the Haskell orchestrator after fork.
 * CPU affinity and SCHED_FIFO are already set by the parent.
 * We open shared memory IPC, connect to JACK, and enter the
 * audio callback loop. The callback must complete within 1.33ms.
 *
 * Usage: demod-rt [--core N] [--faust-lib path.so] [--faust-slot N path.so] ...
 */

#include "demod_rt_audio.h"
#include <signal.h>
#include <unistd.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>
#include <dlfcn.h>

static volatile sig_atomic_t g_running = 1;

static void handle_signal(int sig) {
    (void)sig;
    g_running = 0;
}

/* ── Faust Plugin Loading ───────────────────────────────────────
 * Load a Faust-generated C backend .so and extract the stable
 * new/init/compute/buildUserInterface entry points.
 *
 * The .so is generated by:
 *   faust -lang c -cn mydsp foo.dsp
 *   cc -shared -fPIC -include demod_faust_glue.h -o foo.so foo.c
 */

typedef void *(*FaustNewFn)(void);
typedef void  (*FaustDeleteFn)(void *dsp);
typedef void  (*FaustInitFn)(void *dsp, int sample_rate);
typedef void  (*FaustComputeFn)(void *dsp, int count, float **in, float **out);
typedef int   (*FaustGetIoFn)(void *dsp);
typedef void  (*FaustBuildUiFn)(void *dsp, UIGlue *ui);

typedef struct FaustUiBinder {
    DemodFxParamDesc *params;
    uint8_t          *param_count;
    DemodInstrumentVoiceState *voice;
    int               instance_index;
    int               zone_index;
    int               next_index;
    int               pending_index;
} FaustUiBinder;

typedef struct FaustPlugin {
    void           *handle;
    void           *dsp[DEMOD_RT_CHANNELS];
    void           *voice_dsp[DEMOD_RT_MAX_INSTRUMENT_VOICES][DEMOD_RT_CHANNELS];
    DemodFxParamDesc params[DEMOD_RT_MAX_FX_PARAMS];
    DemodInstrumentVoiceState voices[DEMOD_RT_MAX_INSTRUMENT_VOICES];
    FaustComputeFn  compute;
    FaustDeleteFn   destroy;
    DemodSlotKind   kind;
    uint8_t         dsp_count;
    uint8_t         voice_count;
    uint8_t         num_inputs;
    uint8_t         num_outputs;
    uint8_t         param_count;
} FaustPlugin;

typedef struct FaustUiProbe {
    uint8_t has_gate;
    uint8_t has_freq;
    uint8_t has_gain;
} FaustUiProbe;

static void faust_plugin_unload(FaustPlugin *fp);

static int faust_load_symbol(void *handle, const char *name,
                             void *dst, size_t dst_size)
{
    void *sym = dlsym(handle, name);
    if (!sym) {
        return -1;
    }

    memset(dst, 0, dst_size);
    size_t copy_size = dst_size < sizeof(sym) ? dst_size : sizeof(sym);
    memcpy(dst, &sym, copy_size);
    return 0;
}

static void faust_ui_noop_open(void *ui, const char *label) {
    (void)ui;
    (void)label;
}

static void faust_ui_noop_close(void *ui) {
    (void)ui;
}

static void faust_ui_noop_bargraph(void *ui, const char *label,
                                   FAUSTFLOAT *zone, FAUSTFLOAT min, FAUSTFLOAT max)
{
    (void)ui;
    (void)label;
    (void)zone;
    (void)min;
    (void)max;
}

static const char *faust_ui_label_text(const char *label) {
    const char *p = label ? label : "";

    while (*p == '[') {
        const char *end = strchr(p, ']');
        if (!end) {
            break;
        }
        p = end + 1;
        while (*p && isspace((unsigned char)*p)) {
            p++;
        }
    }

    return p;
}

static int faust_ui_label_matches(const char *label, const char *target) {
    const char *p = faust_ui_label_text(label);
    char buf[64];
    size_t len = 0;

    while (*p && *p != '[' && len + 1 < sizeof(buf)) {
        buf[len++] = (char)tolower((unsigned char)*p++);
    }

    while (len > 0 && isspace((unsigned char)buf[len - 1])) {
        len--;
    }
    buf[len] = '\0';

    return strcmp(buf, target) == 0;
}

static int faust_ui_instrument_control(const char *label) {
    if (faust_ui_label_matches(label, DEMOD_FAUST_LABEL_GATE)) return 1;
    if (faust_ui_label_matches(label, DEMOD_FAUST_LABEL_FREQ)) return 2;
    if (faust_ui_label_matches(label, DEMOD_FAUST_LABEL_GAIN)) return 3;
    return 0;
}

static int faust_ui_resolve_index(FaustUiBinder *binder) {
    int idx = binder->pending_index;
    binder->pending_index = -1;

    if (idx >= 0 && idx < 16) {
        if (idx >= binder->next_index) {
            binder->next_index = idx + 1;
        }
        return idx;
    }

    if (binder->next_index >= 16) {
        return -1;
    }

    return binder->next_index++;
}

static void faust_ui_bind_control(void *ui, const char *label, FAUSTFLOAT *zone,
                                  FAUSTFLOAT init, FAUSTFLOAT min,
                                  FAUSTFLOAT max, FAUSTFLOAT step)
{
    (void)step;

    FaustUiBinder *binder = (FaustUiBinder *)ui;
    int instrument_control = faust_ui_instrument_control(label);

    if (binder->voice && instrument_control != 0) {
        if (binder->instance_index >= 0 && binder->instance_index < DEMOD_RT_CHANNELS) {
            if (instrument_control == 1) {
                binder->voice->gate_zone[binder->instance_index] = zone;
            } else if (instrument_control == 2) {
                binder->voice->freq_zone[binder->instance_index] = zone;
            } else if (instrument_control == 3) {
                binder->voice->gain_zone[binder->instance_index] = zone;
            }
        }
        binder->pending_index = -1;
        return;
    }

    int idx = faust_ui_resolve_index(binder);
    if (idx < 0 || idx >= DEMOD_RT_MAX_FX_PARAMS
        || binder->zone_index < 0
        || binder->zone_index >= DEMOD_RT_MAX_PARAM_ZONES) {
        return;
    }

    binder->params[idx].zone[binder->zone_index] = zone;
    if (binder->zone_index == 0) {
        binder->params[idx].init = init;
        binder->params[idx].min = min;
        binder->params[idx].max = max;
    }
    if ((uint8_t)(binder->zone_index + 1) > binder->params[idx].zone_count) {
        binder->params[idx].zone_count = (uint8_t)(binder->zone_index + 1);
    }

    if ((uint8_t)(idx + 1) > *binder->param_count) {
        *binder->param_count = (uint8_t)(idx + 1);
    }
}

static void faust_ui_add_button(void *ui, const char *label, FAUSTFLOAT *zone) {
    faust_ui_bind_control(ui, label, zone, 0.0f, 0.0f, 1.0f, 1.0f);
}

static void faust_ui_add_check_button(void *ui, const char *label, FAUSTFLOAT *zone) {
    faust_ui_bind_control(ui, label, zone, 0.0f, 0.0f, 1.0f, 1.0f);
}

static void faust_ui_declare(void *ui, FAUSTFLOAT *zone,
                             const char *key, const char *value)
{
    (void)zone;
    (void)value;

    FaustUiBinder *binder = (FaustUiBinder *)ui;
    char *end = NULL;
    long idx = strtol(key, &end, 10);

    if (end && *end == '\0' && idx >= 0 && idx < DEMOD_RT_MAX_FX_PARAMS) {
        binder->pending_index = (int)idx;
    } else {
        binder->pending_index = -1;
    }
}

static void faust_ui_probe_declare(void *ui, FAUSTFLOAT *zone,
                                   const char *key, const char *value)
{
    (void)ui;
    (void)zone;
    (void)key;
    (void)value;
}

static void faust_ui_probe_control(void *ui, const char *label, FAUSTFLOAT *zone,
                                   FAUSTFLOAT init, FAUSTFLOAT min,
                                   FAUSTFLOAT max, FAUSTFLOAT step)
{
    (void)zone;
    (void)init;
    (void)min;
    (void)max;
    (void)step;

    FaustUiProbe *probe = (FaustUiProbe *)ui;
    if (faust_ui_label_matches(label, DEMOD_FAUST_LABEL_GATE)) probe->has_gate = 1;
    if (faust_ui_label_matches(label, DEMOD_FAUST_LABEL_FREQ)) probe->has_freq = 1;
    if (faust_ui_label_matches(label, DEMOD_FAUST_LABEL_GAIN)) probe->has_gain = 1;
}

static void faust_ui_probe_button(void *ui, const char *label, FAUSTFLOAT *zone) {
    faust_ui_probe_control(ui, label, zone, 0.0f, 0.0f, 1.0f, 1.0f);
}

static DemodSlotKind faust_plugin_probe_kind(void *dsp, FaustBuildUiFn build_ui) {
    FaustUiProbe probe = {0, 0, 0};
    if (!build_ui) {
        return DEMOD_SLOT_FX;
    }

    UIGlue ui = {
        .uiInterface = &probe,
        .openTabBox = faust_ui_noop_open,
        .openHorizontalBox = faust_ui_noop_open,
        .openVerticalBox = faust_ui_noop_open,
        .closeBox = faust_ui_noop_close,
        .addButton = faust_ui_probe_button,
        .addCheckButton = faust_ui_probe_button,
        .addVerticalSlider = faust_ui_probe_control,
        .addHorizontalSlider = faust_ui_probe_control,
        .addNumEntry = faust_ui_probe_control,
        .addHorizontalBargraph = faust_ui_noop_bargraph,
        .addVerticalBargraph = faust_ui_noop_bargraph,
        .declare = faust_ui_probe_declare
    };
    build_ui(dsp, &ui);

    return (probe.has_gate || probe.has_freq || probe.has_gain)
        ? DEMOD_SLOT_INSTRUMENT
        : DEMOD_SLOT_FX;
}

static int faust_plugin_bind_params(FaustPlugin *fp, FaustBuildUiFn build_ui) {
    memset(fp->params, 0, sizeof(fp->params));
    fp->param_count = 0;

    if (!build_ui) {
        return 0;
    }

    for (int inst = 0; inst < fp->dsp_count; inst++) {
        FaustUiBinder binder = {
            .params = fp->params,
            .param_count = &fp->param_count,
            .voice = NULL,
            .instance_index = inst,
            .zone_index = inst,
            .next_index = 0,
            .pending_index = -1
        };
        UIGlue ui = {
            .uiInterface = &binder,
            .openTabBox = faust_ui_noop_open,
            .openHorizontalBox = faust_ui_noop_open,
            .openVerticalBox = faust_ui_noop_open,
            .closeBox = faust_ui_noop_close,
            .addButton = faust_ui_add_button,
            .addCheckButton = faust_ui_add_check_button,
            .addVerticalSlider = faust_ui_bind_control,
            .addHorizontalSlider = faust_ui_bind_control,
            .addNumEntry = faust_ui_bind_control,
            .addHorizontalBargraph = faust_ui_noop_bargraph,
            .addVerticalBargraph = faust_ui_noop_bargraph,
            .declare = faust_ui_declare
        };
        build_ui(fp->dsp[inst], &ui);
    }

    return 0;
}

static int faust_plugin_bind_instrument(FaustPlugin *fp, FaustBuildUiFn build_ui) {
    memset(fp->params, 0, sizeof(fp->params));
    memset(fp->voices, 0, sizeof(fp->voices));
    fp->param_count = 0;

    if (!build_ui) {
        return 0;
    }

    for (int voice = 0; voice < fp->voice_count; voice++) {
        for (int inst = 0; inst < fp->dsp_count; inst++) {
            FaustUiBinder binder = {
                .params = fp->params,
                .param_count = &fp->param_count,
                .voice = &fp->voices[voice],
                .instance_index = inst,
                .zone_index = voice * fp->dsp_count + inst,
                .next_index = 0,
                .pending_index = -1
            };
            UIGlue ui = {
                .uiInterface = &binder,
                .openTabBox = faust_ui_noop_open,
                .openHorizontalBox = faust_ui_noop_open,
                .openVerticalBox = faust_ui_noop_open,
                .closeBox = faust_ui_noop_close,
                .addButton = faust_ui_add_button,
                .addCheckButton = faust_ui_add_check_button,
                .addVerticalSlider = faust_ui_bind_control,
                .addHorizontalSlider = faust_ui_bind_control,
                .addNumEntry = faust_ui_bind_control,
                .addHorizontalBargraph = faust_ui_noop_bargraph,
                .addVerticalBargraph = faust_ui_noop_bargraph,
                .declare = faust_ui_declare
            };
            build_ui(fp->voice_dsp[voice][inst], &ui);
        }

        fp->voices[voice].note = 255;
        demod_rt_voice_set_zone(fp->voices[voice].gate_zone, 0.0f);
        demod_rt_voice_set_zone(fp->voices[voice].freq_zone, 440.0f);
        demod_rt_voice_set_zone(fp->voices[voice].gain_zone, 0.0f);
    }

    return 0;
}

static int faust_plugin_load(FaustPlugin *fp, const char *path, int sample_rate) {
    memset(fp, 0, sizeof(*fp));

    fp->handle = dlopen(path, RTLD_NOW | RTLD_LOCAL);
    if (!fp->handle) {
        fprintf(stderr, "[demod-rt] dlopen(%s): %s\n", path, dlerror());
        return -1;
    }

    FaustNewFn new_fn = NULL;
    FaustInitFn init_fn = NULL;
    FaustGetIoFn get_num_inputs_fn = NULL;
    FaustGetIoFn get_num_outputs_fn = NULL;
    FaustBuildUiFn build_ui_fn = NULL;

    (void)faust_load_symbol(fp->handle, "buildUserInterfacemydsp",
                            &build_ui_fn, sizeof(build_ui_fn));

    if (faust_load_symbol(fp->handle, "newmydsp", &new_fn, sizeof(new_fn)) < 0
        || faust_load_symbol(fp->handle, "initmydsp", &init_fn, sizeof(init_fn)) < 0
        || faust_load_symbol(fp->handle, "getNumInputsmydsp",
                             &get_num_inputs_fn, sizeof(get_num_inputs_fn)) < 0
        || faust_load_symbol(fp->handle, "getNumOutputsmydsp",
                             &get_num_outputs_fn, sizeof(get_num_outputs_fn)) < 0
        || faust_load_symbol(fp->handle, "computemydsp",
                             &fp->compute, sizeof(fp->compute)) < 0
        || faust_load_symbol(fp->handle, "deletemydsp",
                             &fp->destroy, sizeof(fp->destroy)) < 0) {
        fprintf(stderr, "[demod-rt] %s: missing required Faust C ABI symbols\n", path);
        dlclose(fp->handle);
        return -1;
    }

    fp->dsp[0] = new_fn();
    if (!fp->dsp[0]) {
        fprintf(stderr, "[demod-rt] %s: failed to allocate DSP\n", path);
        dlclose(fp->handle);
        return -1;
    }
    init_fn(fp->dsp[0], sample_rate);

    fp->num_inputs = (uint8_t)get_num_inputs_fn(fp->dsp[0]);
    fp->num_outputs = (uint8_t)get_num_outputs_fn(fp->dsp[0]);
    fp->kind = faust_plugin_probe_kind(fp->dsp[0], build_ui_fn);

    if (fp->kind == DEMOD_SLOT_INSTRUMENT) {
        fp->voice_dsp[0][0] = fp->dsp[0];
        if (fp->num_outputs == 1 && fp->num_inputs <= 1) {
            fp->dsp_count = 2;
        } else if (fp->num_outputs == 2 && fp->num_inputs <= 2) {
            fp->dsp_count = 1;
        } else {
            fprintf(stderr, "[demod-rt] %s: unsupported instrument shape %u in / %u out\n",
                    path, fp->num_inputs, fp->num_outputs);
            faust_plugin_unload(fp);
            return -1;
        }

        fp->voice_count = DEMOD_RT_MAX_INSTRUMENT_VOICES;
        for (int voice = 0; voice < fp->voice_count; voice++) {
            for (int inst = 0; inst < fp->dsp_count; inst++) {
                if (voice == 0 && inst == 0) {
                    continue;
                }
                fp->voice_dsp[voice][inst] = new_fn();
                if (!fp->voice_dsp[voice][inst]) {
                    fprintf(stderr, "[demod-rt] %s: failed to allocate instrument voice %d/%d\n",
                            path, voice, inst);
                    faust_plugin_unload(fp);
                    return -1;
                }
                init_fn(fp->voice_dsp[voice][inst], sample_rate);
            }
        }

        fp->dsp[0] = fp->voice_dsp[0][0];
        if (fp->dsp_count > 1) {
            fp->dsp[1] = fp->voice_dsp[0][1];
        }

        faust_plugin_bind_instrument(fp, build_ui_fn);
    } else {
        if (fp->num_inputs == 1 && fp->num_outputs == 1) {
            fp->dsp[1] = new_fn();
            if (!fp->dsp[1]) {
                fprintf(stderr, "[demod-rt] %s: failed to allocate right-channel DSP\n", path);
                faust_plugin_unload(fp);
                return -1;
            }
            init_fn(fp->dsp[1], sample_rate);
            fp->dsp_count = 2;
        } else if (fp->num_inputs == 2 && fp->num_outputs == 2) {
            fp->dsp_count = 1;
        } else {
            fprintf(stderr, "[demod-rt] %s: unsupported DSP shape %u in / %u out\n",
                    path, fp->num_inputs, fp->num_outputs);
            faust_plugin_unload(fp);
            return -1;
        }

        faust_plugin_bind_params(fp, build_ui_fn);
    }

    return 0;
}

static void faust_plugin_unload(FaustPlugin *fp) {
    if (fp->destroy) {
        if (fp->kind == DEMOD_SLOT_INSTRUMENT) {
            for (int voice = 0; voice < DEMOD_RT_MAX_INSTRUMENT_VOICES; voice++) {
                for (int inst = 0; inst < DEMOD_RT_CHANNELS; inst++) {
                    if (fp->voice_dsp[voice][inst]) {
                        fp->destroy(fp->voice_dsp[voice][inst]);
                    }
                }
            }
        } else {
            for (int i = 0; i < DEMOD_RT_CHANNELS; i++) {
                if (fp->dsp[i]) {
                    fp->destroy(fp->dsp[i]);
                }
            }
        }
    }
    if (fp->handle) dlclose(fp->handle);
    memset(fp, 0, sizeof(*fp));
}

static const char *parse_faust_slot_spec(const char *spec,
                                         DemodSlotKind *kind,
                                         int *has_kind)
{
    *has_kind = 0;
    if (strncmp(spec, "instrument:", 11) == 0) {
        *kind = DEMOD_SLOT_INSTRUMENT;
        *has_kind = 1;
        return spec + 11;
    }
    if (strncmp(spec, "fx:", 3) == 0) {
        *kind = DEMOD_SLOT_FX;
        *has_kind = 1;
        return spec + 3;
    }
    return spec;
}

/* ── Main ──────────────────────────────────────────────────────── */

int main(int argc, char *argv[]) {
    int rt_core = 4;  /* Default: physical core 2, logical thread 4 (HT enabled) */
    const char *faust_libs[DEMOD_RT_MAX_FX_SLOTS];
    DemodSlotKind faust_kinds[DEMOD_RT_MAX_FX_SLOTS];
    int faust_has_kind[DEMOD_RT_MAX_FX_SLOTS];
    int faust_count = 0;
    memset(faust_libs, 0, sizeof(faust_libs));
    memset(faust_kinds, 0, sizeof(faust_kinds));
    memset(faust_has_kind, 0, sizeof(faust_has_kind));

    /* Parse args */
    for (int i = 1; i < argc; i++) {
        if (strcmp(argv[i], "--core") == 0 && i + 1 < argc) {
            rt_core = atoi(argv[++i]);
        } else if (strcmp(argv[i], "--faust-slot") == 0 && i + 2 < argc) {
            int slot = atoi(argv[++i]);
            if (slot >= 0 && slot < DEMOD_RT_MAX_FX_SLOTS) {
                const char *raw = argv[++i];
                faust_libs[slot] = parse_faust_slot_spec(raw, &faust_kinds[slot],
                                                         &faust_has_kind[slot]);
            } else {
                i++;
            }
        } else if (strcmp(argv[i], "--faust-lib") == 0 && i + 1 < argc) {
            const char *raw = argv[++i];
            while (faust_count < DEMOD_RT_MAX_FX_SLOTS && faust_libs[faust_count] != NULL) {
                faust_count++;
            }
            if (faust_count < DEMOD_RT_MAX_FX_SLOTS) {
                faust_libs[faust_count] = parse_faust_slot_spec(raw,
                    &faust_kinds[faust_count], &faust_has_kind[faust_count]);
                faust_count++;
            }
        }
    }

    faust_count = 0;
    for (int i = 0; i < DEMOD_RT_MAX_FX_SLOTS; i++) {
        if (faust_libs[i] != NULL) {
            faust_count++;
        }
    }

    /* Signal handling (sigaction, not signal) */
    struct sigaction sa = { .sa_handler = handle_signal, .sa_flags = 0 };
    sigemptyset(&sa.sa_mask);
    sigaction(SIGTERM, &sa, NULL);
    sigaction(SIGINT,  &sa, NULL);

    fprintf(stderr, "[demod-rt] starting on core %d, %d Faust plugins\n",
            rt_core, faust_count);

    /* Init engine */
    DemodRtEngine eng;
    int rc = demod_rt_engine_init(&eng, rt_core);
    if (rc < 0) {
        fprintf(stderr, "[demod-rt] engine init failed: %d\n", rc);
        return 1;
    }

    /* Load Faust plugins into FX slots */
    FaustPlugin faust_plugins[DEMOD_RT_MAX_FX_SLOTS];
    memset(faust_plugins, 0, sizeof(faust_plugins));
    jack_nframes_t sr = jack_get_sample_rate(eng.jack_client);

    for (int slot = 0; slot < DEMOD_RT_MAX_FX_SLOTS; slot++) {
        if (faust_libs[slot] == NULL) {
            continue;
        }

        if (faust_plugin_load(&faust_plugins[slot], faust_libs[slot], (int)sr) == 0) {
            memcpy(eng.fx_slots[slot].dsp, faust_plugins[slot].dsp, sizeof(eng.fx_slots[slot].dsp));
            memcpy(eng.fx_slots[slot].voice_dsp, faust_plugins[slot].voice_dsp,
                   sizeof(eng.fx_slots[slot].voice_dsp));
            memcpy(eng.fx_slots[slot].params, faust_plugins[slot].params, sizeof(eng.fx_slots[slot].params));
            memcpy(eng.fx_slots[slot].voices, faust_plugins[slot].voices, sizeof(eng.fx_slots[slot].voices));
            eng.fx_slots[slot].compute = faust_plugins[slot].compute;
            eng.fx_slots[slot].kind = faust_plugins[slot].kind;
            eng.fx_slots[slot].dsp_count = faust_plugins[slot].dsp_count;
            eng.fx_slots[slot].voice_count = faust_plugins[slot].voice_count;
            eng.fx_slots[slot].num_inputs = faust_plugins[slot].num_inputs;
            eng.fx_slots[slot].num_outputs = faust_plugins[slot].num_outputs;
            eng.fx_slots[slot].param_count = faust_plugins[slot].param_count;
            eng.fx_slots[slot].active = 1;
            if (faust_has_kind[slot] && faust_kinds[slot] != eng.fx_slots[slot].kind) {
                fprintf(stderr,
                        "[demod-rt] warning: slot %d requested %s but DSP probed as %s\n",
                        slot,
                        faust_kinds[slot] == DEMOD_SLOT_INSTRUMENT ? "instrument" : "fx",
                        eng.fx_slots[slot].kind == DEMOD_SLOT_INSTRUMENT ? "instrument" : "fx");
            }
            if (eng.fx_slot_count < slot + 1) {
                eng.fx_slot_count = slot + 1;
            }
            fprintf(stderr,
                    "[demod-rt] loaded %s slot %d: %s (%u in/%u out, %u params)\n",
                    eng.fx_slots[slot].kind == DEMOD_SLOT_INSTRUMENT ? "instrument" : "FX",
                    slot, faust_libs[slot],
                    eng.fx_slots[slot].num_inputs,
                    eng.fx_slots[slot].num_outputs,
                    eng.fx_slots[slot].param_count);
        }
    }

    /* Activate JACK */
    rc = demod_rt_engine_activate(&eng);
    if (rc != 0) {
        fprintf(stderr, "[demod-rt] JACK activate failed\n");
        demod_rt_engine_shutdown(&eng);
        for (int slot = 0; slot < DEMOD_RT_MAX_FX_SLOTS; slot++) {
            faust_plugin_unload(&faust_plugins[slot]);
        }
        return 1;
    }

    fprintf(stderr, "[demod-rt] active — sr=%u buf=%u (%.3fms)\n",
            (unsigned)sr, (unsigned)jack_get_buffer_size(eng.jack_client),
            (double)jack_get_buffer_size(eng.jack_client) / (double)sr * 1000.0);

    /* Main loop: just sleep, the callback does all the work */
    while (g_running) {
        usleep(100000); /* 100ms — only for signal handling */
    }

    fprintf(stderr, "[demod-rt] shutting down — %lu callbacks, %lu xruns, cpu=%.1f%%\n",
            (unsigned long)eng.callback_count,
            (unsigned long)eng.xrun_count,
            (double)eng.cpu_load * 100.0);

    /* Cleanup */
    demod_rt_engine_shutdown(&eng);
    for (int slot = 0; slot < DEMOD_RT_MAX_FX_SLOTS; slot++)
        faust_plugin_unload(&faust_plugins[slot]);

    return 0;
}
